/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.codegym;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class FoodForm extends javax.swing.JFrame {

    /**
     * Creates new form FoodForm
     */
    public FoodForm() {
        initComponents();
        showTime();
        
        this.setLocationRelativeTo(null);
    }
        public void showTime() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date currentTimeDate = new Date();
                txtTimerDemo.setText(currentTimeDate.toString());
            }
        } );
        timer.start();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblFood = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        txtChoice = new javax.swing.JMenu();
        txtBack = new javax.swing.JMenuItem();
        txtLogout = new javax.swing.JMenuItem();
        txtExit = new javax.swing.JMenuItem();
        txtTimerDemo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblFood.setForeground(new java.awt.Color(255, 165, 2));
        tblFood.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-11-600x400.jpg"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea1.setRows(5);
        jTextArea1.setText("\nNhìn mâm cơm bên dưới, liệu tinh thần ăn \nuống của bạn đã đi lên chưa? Chắc hẳn bạn \ncũng nắm rõ cách chế biến những món ăn \nquen thuộc này rồi nhỉ?\n\nCác món chính:\n--------------------------------\n1. Canh ngao\n--------------------------------\n2. Dưa cải muối chua\n--------------------------------\n3. Sườn xào chua ngọt\n--------------------------------\n4. Thịt xào ngồng tỏi\n--------------------------------\n5. Hoa quả tráng miệng");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        tblFood.addTab("Thực đơn 1", jPanel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-12-600x400.jpg"))); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea2.setRows(5);
        jTextArea2.setText("\nƯu tiên rau trong bữa ăn của gia đình sẽ tốt \nchosức khỏe của bạn. Vì vậy không có lí do gì\nchúng ta không triển khai một mâm cơm như\nthế này nhỉ:\n\nCác món chính:\n--------------------------------\n1. Canh cua cà muối\n--------------------------------\n2. Mướp xào thịt lợn\n--------------------------------\n3. Su su luộc\n--------------------------------\n4. Thịt lợn rang");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        tblFood.addTab("Thực đơn 2", jPanel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-14-600x400.jpg"))); // NOI18N

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea3.setRows(5);
        jTextArea3.setText("\nCác món ăn từ thịt lợn luôn gần gũi với chúng\nta nhất. Có rất nhiều món ăn ngon từ thịt lợn \nbạn có thể tham khảo thực đơn dưới đây nhé.\n\nCác món chính:\n---------------------------\n1. Canh xương\n---------------------------\n2. Bí ngô xào tỏi\n---------------------------\n3. Thịt lợn luộc\n---------------------------\n4. Hoa quả tráng miệng");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tblFood.addTab("Thực đơn 3", jPanel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-15-600x400.jpg"))); // NOI18N

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea4.setRows(5);
        jTextArea4.setText("\nBữa cơm dành cho gia đình không bị xem là \nsơ sài nếu bạn áp dụng mâm cơm như gợi ý \ndưới đây. Đây là thực đơn được hưởng ứng \nbởi sự đơn giản, đẹp mắt mà vẫn đầy đủ \ndinh dưỡng cho gia đình bạn!\n\nCác món chính:\n------------------------\n1. Thịt chân giò luộc\n------------------------\n2. Canh mướp\n------------------------\n3. Canh cá nấu chua\n------------------------\n4. Đậu đũa xào lòng");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tblFood.addTab("Thực đơn 4", jPanel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-16-600x400.jpg"))); // NOI18N

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea5.setRows(5);
        jTextArea5.setText("\nNhững ngày cuối tuần bạn có thể làm một \nmâm cơm với đa dạng món một chút để chiêu\nđãi cả gia đình. Những món ăn dưới đây sẽ là \ngợi ý hay cho bạn. Rau quả được sử dụng khá\nnhiều để tránh bị ngán bởi những đồ ăn nhiều\ndầu mỡ!\n\nCác món chính:\n------------------------------\n1. Tôm nõn rim mắm\n------------------------------\n2. Canh chua\n------------------------------\n3. Cải thảo luộc\n------------------------------\n4. Dưa chuột góp\n------------------------------\n5. Sườn sụn rang");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );

        tblFood.addTab("Thực đơn 5", jPanel5);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-18-600x400.jpg"))); // NOI18N

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea6.setRows(5);
        jTextArea6.setText("\nThịt lợn và cá là những thực phẩm bổ dưỡng \nđã quá quen thuộc trong mâm cơm của người\nViệt. Cho dù bạn ở bất cứ vùng miền nào, \nmâm cơm dưới đây đều phù hợp cho gia đình \ncủa bạn. Rau sống đi kèm với canh chua cũng\nđược xem là sự kết hợp thông minh giúp cho \nmâm cơm thêm đậm đà hương vị!\n\nCác món chính:\n----------------------------\n1. Thịt ba chỉ chiên giòn\n----------------------------\n2. Chanh cá nấu chua\n----------------------------\n3. Cá rán giòn\n----------------------------\n4. Rau sống ăn kèm");
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );

        tblFood.addTab("Thực đơn 6", jPanel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-3-600x400.jpg"))); // NOI18N

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea7.setRows(5);
        jTextArea7.setText("\nMột thực đơn chế biến nhanh và đủ dinh \ndưỡng sẽ bao gồm những gì nhỉ. Đây là mâm \ncơm sẽ giúp bạn không mất quá nhiều thời \ngian cho việc bếp núc mà vẫn sẽ nhận được \nkhen tới tấp bởi ngon miệng!\n\nCác món chính:\n-------------------------------\n1. Đậu rán chấm mắm tôm\n-------------------------------\n2. Gà rang\n-------------------------------\n3. Lạc rang\n-------------------------------\n4. Rau thơm ăn kèm");
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
        );

        tblFood.addTab("Thực đơn 7", jPanel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-5-600x400.jpg"))); // NOI18N

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea8.setRows(5);
        jTextArea8.setText("\nThêm một gợi ý bữa cơm nhanh gọn đơn giản\nnữa cho bạn trổ tài. Chỉ nhìn mâm cơm thôi \ncũng đủ ứa nước miếng rồi. Bạn sẽ chỉ mất \nkhoảng 30 phút để có một bữa cơm gia đình \nngon lành như thế này. Thật khó cưỡng lại \ntrước sự thơm ngon của thức ăn đúng không!\n\nCác món chính:\n-----------------------\n1. Đậu rán giòn\n-----------------------\n2. Cá rô rán giòn\n-----------------------\n3. Canh cua cà muối\n-----------------------\n4. Rau muống luộc\n-----------------------\n5. Lòng lợn luộc");
        jScrollPane8.setViewportView(jTextArea8);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane8)
        );

        tblFood.addTab("Thực đơn 8", jPanel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-6-600x400.jpg"))); // NOI18N

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea9.setRows(5);
        jTextArea9.setText("\nNếu gia đình bạn có 2-3 người ăn, bạn có thể \ntham khảo mâm cơm gia đình dưới đây. \nKhông có món ăn có quá nhiều dầu mỡ mà \nvẫn đảm bảo chất dinh dưỡng cho cả gia đình\nbạn. Các món ăn trong mâm cơm này thiên \nvề đồ hải sản với:\n\nCác món chính:\n------------------------\n1. Cá kho tộ\n------------------------\n2. Đậu đũa luộc\n------------------------\n3. Chả cá sốt cà chua\n------------------------\n4. Cà muối");
        jScrollPane9.setViewportView(jTextArea9);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane9)
        );

        tblFood.addTab("Thực đơn 9", jPanel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-8-600x400.jpg"))); // NOI18N

        jTextArea10.setEditable(false);
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea10.setRows(5);
        jTextArea10.setText("\nThử thực hiện một mâm cơm trong vòng 30 \nphút xem nào. Đây là mâm cơm ưu tiên rau \nxanh nên ăn thanh mát, nhẹ nhành, đưa cơm.\nBạn sẽ không phải lo ngán ngấy với những \nmón ăn ngập trong dầu mỡ. \nMâm cơm gồm những món!\n\nCác món chính:\n--------------------------\n1. Dưa cải muối chua\n--------------------------\n2. Canh mướp lòng gà\n--------------------------\n3. Thịt ba chỉ kho tàu\n--------------------------\n4. Lạc rang muối\n--------------------------\n5. Rau muống luộc");
        jScrollPane10.setViewportView(jTextArea10);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane10)
        );

        tblFood.addTab("Thực đơn 10", jPanel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thuc-don-bua-com-gia-dinh-9-600x400.jpg"))); // NOI18N

        jTextArea11.setEditable(false);
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea11.setForeground(new java.awt.Color(55, 66, 250));
        jTextArea11.setRows(5);
        jTextArea11.setText("\nMột mâm cơm truyền thống luôn khiến cho \nmọi người nức nở khen ngợi. Không cần nhiều\nmón ăn cầu kì, mọi người vẫn phải trầm trồ \ntrước tài nấu ăn của bạn. Dù bạn có vụng đến\nđâu thì những món ăn dưới đây cũng được \nthực hiện dễ dàng:\n\nCác món chính:\n-------------------------\n1. Rau bí luộc\n-------------------------\n2. Sườn xào dứa\n-------------------------\n3. Canh bầu nấu ngao\n-------------------------\n4. Đậu rán\n-------------------------\nCà muối chua ngọt");
        jScrollPane11.setViewportView(jTextArea11);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jScrollPane11)
        );

        tblFood.addTab("Thực đơn 11", jPanel11);

        txtChoice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        txtChoice.setForeground(new java.awt.Color(51, 0, 255));
        txtChoice.setText("File");
        txtChoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBack.setText("Back");
        txtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackActionPerformed(evt);
            }
        });
        txtChoice.add(txtBack);

        txtLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLogout.setText("Logout");
        txtLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogoutActionPerformed(evt);
            }
        });
        txtChoice.add(txtLogout);

        txtExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtExit.setText("Exit");
        txtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExitActionPerformed(evt);
            }
        });
        txtChoice.add(txtExit);

        jMenuBar2.add(txtChoice);

        txtTimerDemo.setForeground(new java.awt.Color(255, 0, 0));
        txtTimerDemo.setText("TimeICT");
        txtTimerDemo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuBar2.add(txtTimerDemo);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(tblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblFood, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackActionPerformed
        // TODO add your handling code here:
        new MenuForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtBackActionPerformed

    private void txtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogoutActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtLogoutActionPerformed

    private void txtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtExitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FoodForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTabbedPane tblFood;
    private javax.swing.JMenuItem txtBack;
    private javax.swing.JMenu txtChoice;
    private javax.swing.JMenuItem txtExit;
    private javax.swing.JMenuItem txtLogout;
    private javax.swing.JMenu txtTimerDemo;
    // End of variables declaration//GEN-END:variables
}
